In [1]:
import tensorflow as tf

#Different Data Structure

In [2]:
a= tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
b=tf.constant([1,2,3,4])
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [4]:
c= tf.constant([[1,2,3,4], [5,6,7,8]])
c

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [5]:
d=tf.constant([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])
d

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]], dtype=int32)>

#Different Opperation


In [6]:
a=tf.constant([1,2]) # 1 Rows , 2 Columns
b=tf.constant([3,4]) # 1 Rows , 2 Columns

In [7]:
# Sum
c=tf.add(a,b)
c

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [8]:
# Subtract
d=tf.subtract(a,b)
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [9]:
# Multiplication
a_1 = tf.constant([[1,2], [3,4]])
b_1 = tf.constant([[5,6], [7,8]])

print(f'a_1 matrix is:\n{a_1}\n \n b_1 matrix is :\n{b_1}')

a_1 matrix is:
[[1 2]
 [3 4]]
 
 b_1 matrix is :
[[5 6]
 [7 8]]


In [10]:
ew = tf.multiply(a_1, b_1)
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [11]:
nm= tf.matmul(a_1,b_1)
nm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [12]:
# Division
a=tf.constant([1,2])
b=tf.constant([3,0])

d=tf.divide(a,b)
d

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.33333333,        inf])>

#Broadcasting

In [13]:
a=tf.constant([1,2,3])
b=tf.constant(4)  # 4 => [4,4,4]
c= a + b
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>

#Reshape

In [14]:
a=tf.constant([1,2,3,4,5,6,7,8,9,10,11,12])
a.shape

TensorShape([12])

In [15]:
b=tf.reshape(a, shape=[2,3,2])
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>

In [16]:
# Add Dimension

In [17]:
a=tf.constant([1,2,3,4,5,6])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [18]:
b=tf.expand_dims(a, axis=0)
b

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

#Operation On Element

In [19]:
a=tf.constant([[1,2,3],
              [4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [20]:
#Square
b=tf.square(a)
b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [21]:
#sqrt
c=tf.sqrt(tf.cast(a,dtype=float))
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.2360678, 2.4494896]], dtype=float32)>

#Min, Max, Mean, STD

In [22]:
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [23]:
#MIN
min = tf.reduce_min(a,axis=1)
min

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [24]:
#MAX
max = tf.reduce_max(a,axis=1)
max

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [25]:
#AVERAGE
avg = tf.reduce_mean(a,axis=1)
avg

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [26]:
#standard deviation
std = tf.math.reduce_std(tf.cast(a,float))
std

<tf.Tensor: shape=(), dtype=float32, numpy=1.7078251>

In [27]:
#SUM
sum = tf.reduce_sum(a, axis=1)
sum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 6, 15], dtype=int32)>